---
- name: init calamari
  shell: calamari-ctl initialize --admin-username admin --admin-password admin --admin-email admin@huawei.com
  args:
    chdir: '{{ ceph_cluster_dir }}'
  tags:
    - create_ceph_cluster

- name: set apache2 listen port
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    insertafter: 'Listen {{ internal_ip }}:80'
    line: 'Listen {{ internal_ip }}:8080'

- name: set virtual host listen port
  template: src=calamari.j2 dest=/etc/httpd/conf.d/calamari.conf mode=0755

- name: restart httpd services
  service: name=httpd state=restarted enabled=yes

- name: create ceph cluster
  shell: ceph-deploy new {{ inventory_hostname }}
  args:
    chdir: '{{ ceph_cluster_dir }}'
  tags:
    - create_ceph_cluster

- name: install ceph-mon for every nodes includes jumpserver
  shell: ceph-deploy install --mon {{ inventory_hostname}}
  args:
    chdir: '{{ ceph_cluster_dir }}'

- name: install ceph-osd for controller node
  shell: ceph-deploy install --osd {{ item }}
  args:
    chdir: '{{ ceph_cluster_dir }}'
  with_items:
    - "{{ groups['compute'] }}"

- name: create monitor node
  shell: ceph-deploy mon create-initial
  args:
    chdir: '{{ ceph_cluster_dir }}'
  ignore_errors: True

- name: sleep for monitor node
  shell: sleep 20

- name: create monitor node again for double check
  shell: ceph-deploy mon create-initial
  args:
    chdir: '{{ ceph_cluster_dir }}'
  ignore_errors: True

- name: copy create_osd.sh to host1
  copy: src=create_osd.sh dest=~/create_osd.sh mode=0777
  tags:
    - create_osd

- name: copy create_osd.sh to other nodes
  shell: scp -o StrictHostKeyChecking=no ~/create_osd.sh {{ item }}:~/
  with_items:
    - "{{ groups['compute'] }}"
  tags:
    - create_osd

- name: exec create osd storage shell
  shell: ssh -o StrictHostKeyChecking=no -t {{ item }} "~/create_osd.sh"
  with_items:
    - "{{ groups['compute'] }}"
  tags:
    - create_osd
  ignore_errors: True

- name: prepare create osd
  shell: ceph-deploy osd prepare {{ item }}:/var/local/osd
  args:
    chdir: '{{ ceph_cluster_dir }}'
  with_items:
    - "{{ groups['compute'] }}"
  tags:
    - create_osd

- name: activate osd
  shell: ceph-deploy osd activate {{ item }}:/var/local/osd
  args:
    chdir: '{{ ceph_cluster_dir }}'
  with_items:
    - "{{ groups['compute'] }}"
  tags:
    - create_osd
    - activate_osd

- name: create admin node
  shell: ceph-deploy admin {{ inventory_hostname }}
  args:
    chdir: '{{ ceph_cluster_dir }}'

- name: connect all nodes to calamari
  shell: ceph-deploy calamari connect --master {{ internal_ip }} {{ inventory_hostname }}
  args:
    chdir: '{{ ceph_cluster_dir }}'
