---
- name: create ceph cluster
  shell: cd {{ ceph_cluster_dir[0] }} && ceph-deploy new {{ ceph_cluster_hosts.stdout_lines[0] }}
  tags:
    - create_ceph_cluster

- name: install ceph-mon for every nodes includes jumpserver
  shell: cd {{ ceph_cluster_dir[0] }} && ceph-deploy install --mon {{ ceph_cluster_hosts.stdout_lines[0]}}

- name: install ceph-osd for controller node
  shell: cd {{ ceph_cluster_dir[0] }} && ceph-deploy install --osd {{ item }}
  with_items:
    - "{{ groups['compute'] }}"

- name: create monitor node
  shell: cd {{ ceph_cluster_dir[0] }} && ceph-deploy mon create-initial
  ignore_errors: True

- name: sleep for monitor node
  shell: sleep 20

- name: create monitor node again for double check
  shell: cd {{ ceph_cluster_dir[0] }} && ceph-deploy mon create-initial 
  ignore_errors: True

- name: copy create_osd.sh to host1
  copy: src=create_osd.sh dest=~/create_osd.sh mode=0777
  tags:
    - create_osd

- name: copy create_osd.sh to other nodes
  shell: scp -o StrictHostKeyChecking=no ~/create_osd.sh {{ item }}:~/
  with_items:
    - "{{ groups['compute'] }}"
  tags:
    - create_osd

- name: exec create osd storage shell
  shell: ssh -o StrictHostKeyChecking=no -t {{ item }} "~/create_osd.sh"
  with_items:
    - "{{ groups['compute'] }}"
  tags:
    - create_osd
  ignore_errors: True

- name: prepare create osd
  shell: cd {{ ceph_cluster_dir[0] }} && ceph-deploy osd prepare {{ item }}:/var/local/osd
  with_items:
    - "{{ groups['compute'] }}"
  tags:
    - create_osd


- name: activate osd
  shell: cd {{ ceph_cluster_dir[0] }} && ceph-deploy osd activate {{ item }}:/var/local/osd
  with_items:
    - "{{ groups['compute'] }}"
  tags:
    - create_osd
    - activate_osd

- name: create admin node
  shell: cd {{ ceph_cluster_dir[0] }} && ceph-deploy admin {{ ceph_cluster_hosts.stdout_lines[0] }}
