---
- include_vars: "{{ ansible_os_family }}.yml"

- name: copy data.sh
  template: src=data.j2 dest=/opt/data.sh mode=777
  tags:
    - mysql_user

- include: mysql.yml
  when: haproxy_hosts is not defined

- include: mariadb.yml
  when: haproxy_hosts is defined

