---
- include_vars: "{{ ansible_os_family }}.yml"

- include: cinder_install.yml
  tags:
    - install
    - cinder-install
    - cinder

- include: cinder_config.yml
  tags:
    - config
    - cinder-config
    - cinder
