nic_mappings: []
bond_mappings: []

provider_net_mappings:
  - name: br-prv
    network: physnet
    interface: eno2
    type: ovs
    role:
      - controller
      - compute

sys_intf_mappings:
  - name: mgmt
    interface: eno2
    vlan_tag: 101
    type: vlan
    role:
      - controller
      - compute

  - name: storage
    interface: eno2
    vlan_tag: 102
    type: vlan
    role:
      - controller
      - compute

  - name: external
    interface: br-prv
    type: ovs
    role:
      - controller
      - compute

ip_settings:
  - name: mgmt
    ip_ranges:
    - - "172.16.1.1"
      - "172.16.1.254"
    cidr: "172.16.1.0/24"
    role:
      - controller
      - compute

  - name: storage
    ip_ranges:
    - - "172.16.2.1"
      - "172.16.2.254"
    cidr: "172.16.2.0/24"
    role:
      - controller
      - compute

  - name: external
    ip_ranges:
    - - "172.29.24.180"
      - "172.29.24.189"
    cidr: "172.29.24.0/24"
    gw: "172.29.24.254"
    role:
      - controller
      - compute

internal_vip:
  ip: 172.16.1.179
  netmask: "24"
  interface: mgmt

public_vip:
  ip: 172.29.24.179
  netmask: "24"
  interface: external

public_net_info:
  enable: False
  network: ext-net
  type: vlan
  segment_id: 1000
  subnet: ext-subnet
  provider_network: physnet
  router: router-ext
  enable_dhcp: False
  no_gateway: False
  external_gw: "172.29.24.254"
  floating_ip_cidr: "172.29.24.0/24"
  floating_ip_start: "172.29.24.190"
  floating_ip_end: "172.29.24.199"
