---
- include_vars: "{{ ansible_os_family }}.yml"
  tags: secgroup

- name: make sure template dir exits
  file: path=/opt/os_templates state=directory mode=0755
  tags: secgroup

- name: copy configs
  template: src={{ item.src}} dest=/opt/os_templates
  with_items: "{{ configs_templates }}"
  tags: secgroup

- name: update controller configs
  shell: crudini --merge {{ item.1 }} < /opt/os_templates/{{ item.0.src }}
  ignore_errors: True
  tags: secgroup
  with_subelements:
    - configs_templates
    - dest
  notify: restart controller relation service
  when: inventory_hostname in "{{ groups['controller'] }}"

- name: update compute configs
  shell: crudini --merge {{ item.1 }} < /opt/os_templates/{{ item.0.src }}
  ignore_errors: True
  tags: secgroup
  with_subelements:
    - configs_templates
    - dest
  notify: restart compute relation service
  when: inventory_hostname in "{{ groups['compute'] }}"
